version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: mssql-2019.Dockerfile
    environment:
      SA_PASSWORD: "Password@12345"
      ACCEPT_EULA: "Y"
    ports:
      - "19876:1433"